### ISSUE TITLE
Hold off on Google Test framework

### ISSUE THREAD

**Issue by gyroknight** [dorothysyu/part2#19]
We've realized that Google Test's death tests work in strange ways that don't actually do what we expect (code that fails normally doesn't trigger the death tests) and multithreading breaks a lot of the tests (`testing::FLAGS_gtest_death_test_style = "threadsafe";` before running tests). Please revert back to the `assert()` based tests and hold off adding Google Tests until validating the framework's expected functionality.

**Comment by dorothysyu** [comment]
Do you think separating out the death cases would solve this? I addressed an issue here https://github.com/dorothysyu/part2/issues/18 where I opened a new branch that separates the cases out

**Comment by gyroknight** [comment]
I think separating them out would be the best case, or even just commenting them out would work.

**Comment by dorothysyu** [comment]
Let me know if separating them out worked, otherwise I will just comment it out (definitely not ideal bc we won't be testing for failures..but .. we all have deadlines here 😬😬😬😬)

**Comment by gyroknight** [comment]
New branch still doesn't work; the death test mechanism is strange (running code in tests manually will cause a crash but doesn't register as death to Google Test for some reason) and needs exploration at another time. I would advise just leaving out the death tests altogether or commenting them out and including an explanation of what the expected result is.

**Comment by dorothysyu** [comment]
commented them out and i pushed this
